#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
# if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
#   source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
# fi
# For claude code
# https://github.com/anthropics/claude-code/issues/783#issuecomment-2803480760
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  if [[ -z "${CLAUDECODE}" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
  fi
fi

# Customize to your needs...

# $(brew --prefix) is too slow!
# brew_prefix="$(brew --prefix)"
brew_prefix='/opt/homebrew'
if [ -f ${brew_prefix}/etc/brew-wrap ];then
  source ${brew_prefix}/etc/brew-wrap
fi

# https://github.com/anyenv/anyenv
export PATH="$HOME/.anyenv/bin:$PATH"
eval "$(anyenv init -)"

# go
export GOPATH=$HOME/dev
export PATH=$PATH:$GOPATH/bin
# for python
export PIPENV_VENV_IN_PROJECT=true
export PATH=$PATH:~/.poetry/bin

# for zlib
export LDFLAGS="-L${brew_prefix}/opt/zlib/lib"
export CPPFLAGS="-I${brew_prefix}/opt/zlib/include"
export PKG_CONFIG_PATH="${brew_prefix}/opt/zlib/lib/pkgconfig"

bindkey '^]' peco-src
function peco-src () {
  local src=$( ghq list --full-path | peco --query "$LBUFFER")
  if [ -n "$src" ]; then
    BUFFER="cd $src"
    zle accept-line
  fi
  zle -R -c
}
zle -N peco-src


function peco-history-selection() {
    BUFFER=`history -n 1 | tail -r  | awk '!a[$0]++' | peco`
    CURSOR=$#BUFFER
    zle reset-prompt
}

alias -g B='`git branch -a | peco --prompt "GIT BRANCH>" | head -n 1 | sed -e "s/^\*\s*//g"`'

zle -N peco-history-selection
bindkey '^R' peco-history-selection

export PATH="/usr/local/opt/openjdk/bin:$PATH"

# Created by `pipx` on 2024-04-30 04:25:53
export PATH="$PATH:/Users/shotat/.local/bin"

# Docker
export PATH="$PATH:/Users/shotat/.docker/bin"
